### ISSUE TITLE
Attempting to create stack in incorrect region

### ISSUE THREAD

**Issue by filipeestacio** [lmammino/org-formation-sso-import#3]
I have an organization in EU-WEST-2. When attempting to run this script with NPX, I notice that it reads the identity-store-id correctly (so assuming that it is understanding that my AWS region has been set correctly in the environment variables). However it is trying to create the SsoAssignments stack in EU-WEST-1 and failing because it can't find the identity-store-id in that region.

**Comment by filipeestacio** [comment]
I think I found the issue. In templates/sso-assignments-base.yml.njk, on line 12, the region is hardcoded as eu-west-1. If you're happy for me to contribute, I'll try to submit a PR to add the ability to pass the correct region into the template. Is there a preferred way to get the region? Maybe through a flag when running the script or from environment variables?

**Comment by lmammino** [comment]
Closed by #4
